// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCEorV-HSCBTlu_RKA7HYddFxxCO2QKM',
    appId: '1:1063441250896:web:42b00aa41456d89cf42f55',
    messagingSenderId: '1063441250896',
    projectId: 'comsats-bizz-buzz',
    authDomain: 'comsats-bizz-buzz.firebaseapp.com',
    databaseURL: 'https://comsats-bizz-buzz-default-rtdb.firebaseio.com',
    storageBucket: 'comsats-bizz-buzz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kMtsRzh66oYYgSTnatgQ1fj-VpGLG34',
    appId: '1:1063441250896:android:eabc9b6219c07d60f42f55',
    messagingSenderId: '1063441250896',
    projectId: 'comsats-bizz-buzz',
    databaseURL: 'https://comsats-bizz-buzz-default-rtdb.firebaseio.com',
    storageBucket: 'comsats-bizz-buzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gDHNRXjcvPtuThPadaFznfXzwH78RqI',
    appId: '1:1063441250896:ios:7d4f0892b9cd5064f42f55',
    messagingSenderId: '1063441250896',
    projectId: 'comsats-bizz-buzz',
    databaseURL: 'https://comsats-bizz-buzz-default-rtdb.firebaseio.com',
    storageBucket: 'comsats-bizz-buzz.appspot.com',
    iosBundleId: 'com.example.cbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-gDHNRXjcvPtuThPadaFznfXzwH78RqI',
    appId: '1:1063441250896:ios:31d92cf6d4feb9b8f42f55',
    messagingSenderId: '1063441250896',
    projectId: 'comsats-bizz-buzz',
    databaseURL: 'https://comsats-bizz-buzz-default-rtdb.firebaseio.com',
    storageBucket: 'comsats-bizz-buzz.appspot.com',
    iosBundleId: 'com.example.cbb.RunnerTests',
  );
}
